before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: f+tNVGBeJACZQp+YiHMT+p3avOt+bj/4bzmswfCFoumMij0HmjVSK2+q2sSsjNx0Ta40uJnSKsoYCYO0Rd4rQitSYS7WT4DCOIj7jCm3ftRBbh8/SRLWBJaBBBUJtxdcVv5Z7yaxtUj3hEQ77rUMKgM3aknNS6dyQVnGLyw9+pAn1JdOlG+wTeyD9FNKcxUv6ZRRRZzY2t8of3AGgaa0e3TyHMdIEDvPxJkPpngdXPjZY4U/LNbnkYfSs4LRzTlvRwfsW582HNxnVlOJEkgE7h9A92AMGFaPqBtqLTJXq6kDQrp9vBmlRaIW7cvdKEapuXWCZ5RGZH7VGQwS+rPxGnku+GQWEg+z7TT0AnG6rjaEzi4O6KN/4VT7/mBfXyhfutNN/cRtnOCvnPDD5bRw0vPaTZJEOoOLVvYkPMpEm1CIEcMOmCDT0iTOCYKnuzQXDn9GIjBIf55PQsmQ8ArTSROD+z0lhZUwkl+l02egjmhXSBrLP2ctKgyfMP99733Vhz2enu7oIi+sLtm7itazM5S95cPdxx7ti5eQW2MluakAmfbTv90S5zafLHARiJlsfLYWyaIKsOz3Dp73TX5GMzoMIvzmbg2mSNfgcuHhxa/vDydNPiOd+yevj11DLgte+2b7wevqiQxwdfiQBWff+CRHSl9hLVLoUkFrhJUmxRQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
